config/routes.rb
Rails.application.routes.draw do


    # 管理者ページ
 namespace :admin do
  resources :users
end

  devise_for :admins, controllers: {
  sessions:      'admin/admins/sessions',
#   passwords:     'admin/admins/passwords',
  # registrations: 'admin/registrations'
}

  root to: 'homes#top'

# 社員ページ

 scope module: :public do
  resources :events
end

  devise_for :users, controllers: {
  sessions:      'public/users/sessions',
#   passwords:     'public/users/passwords',
  # registrations: 'public/users/registrations'
}



end

app/views/admin/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav_btn"><%= link_to '社員登録', new_admin_user_path, class: "btn btn-outline-secondary btn-md text-dark btn btn-light" %></li>
          <li class="nav_btn"><%= link_to '社員一覧', admin_users_path, class: "btn btn-outline-secondary btn-md text-dark btn btn-light" %></li>
          <li class="nav_btn"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary btn-md text-dark btn btn-light" %></li>
        </ul>
      </div>
  </div>
  </nav>
</header>