config/routes.rb
Rails.application.routes.draw do


    # 管理者ページ
 namespace :admin do
  resources :users
end

  devise_for :admins, controllers: {
  sessions:      'admin/admins/sessions',
#   passwords:     'admin/admins/passwords',
  # registrations: 'admin/registrations'
}

  root to: 'homes#top'

# 社員ページ

 scope module: :public do
  resources :events
end

  devise_for :users, controllers: {
  sessions:      'public/users/sessions',
#   passwords:     'public/users/passwords',
  # registrations: 'public/users/registrations'
}



end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = 'タスクが投稿されました'
      redirect_to events_path
    else
      flash[:danger] = 'タスクが投稿されません'
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

   if @event.update(event_params)
    flash[:success] = 'タスクが編集されました'
    redirect_to @event
   else
    flash.now[:danger] = 'タスクが編集されませんでした'
    render :edit
   end
  end

  def destroy
   @event = Event.find(params[:id])
   @event.destroy

   flash[:success] = 'タスクが削除されました'
   redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :start_time)
  end

end

app/views/events/edit.html.erb
<h1>タスク投稿</h1>

<%= form_with model: @event, url: event_path, local:true do |f| %>

  <div class="title">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>

    <div class="time">
    <%= f.label :開始時間ー終了時間 %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= f.label :タスク内容 %>
    <%= f.text_area :content %>
  </div>


  <div class="submit">
    <%= f.submit %>
  </div>

<% end %>

app/views/events/index.html.erb
<div class="toppage">
<h1 class="top">カレンダー</h1>



<div class="col-md-8">
<%= week_calendar events: @events do |date, events| %>
  <%= date.day %>

    <div>
      <%= link_to '＋', new_event_path(date) %>
    </div>
  <% events.each do |event| %>
    <div>
      <%= link_to event.title, event %>
    </div>
  <% end %>
<% end %>
</div>
</div>
</div>

app/views/events/new.html.erb
<h1>タスク投稿</h1>

<%= form_with model: @event, url: events_path, local:true do |f| %>

  <div class="title">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>

    <div class="time">
    <%= f.label :開始時間ー終了時間 %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= f.label :タスク内容 %>
    <%= f.text_area :content %>
  </div>


  <div class="submit">
    <%= f.submit %>
  </div>

<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
<p>
  <strong>タイトル</strong>
  <%= @event.title %>
</p>

<p>
  <strong>内容</strong>
  <%= @event.content %>
</p>

<p>
  <strong>日時</strong>
  <%= @event.start_time.strftime("%m-%d") %>
</p>

<%= link_to '編集', edit_event_path(@event) %>
<%= link_to '消去', event_path(@event.id), method: :delete, data: { confirm: '本当に?' } %>
<%= link_to '戻る', events_path %>
</div>